name: Selenium TestNG Allure Workflow

on:
  push:
    branches:
      - master

env:
  MAVEN_OPTS: "-Dmaven.repo.local=maven-repo"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Maven
        uses: actions/setup-java@v1
        with:
          java-home: "${{ env.JAVA_HOME }}"
          maven-version: 3.6.3

      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Maven
        uses: actions/setup-java@v1
        with:
          java-home: "${{ env.JAVA_HOME }}"
          maven-version: 3.6.3

      - name: Run TestNG tests with Allure
        run: mvn clean test allure:report
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=maven-repo"

  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish Allure Report
        uses: actions/upload-artifact@v1
        with:
          name: allure-report
          path: allure-report
